"Package meta information"
__title__ = "openlr_dereferencer"
__description__ = "OpenLR location dereferencer"
__url__ = "https://github.com/tomtom-international/openlr-python-dereferencer"
__version__ = "0.9"
__author__ = "Jan Ole Zabel"
__author_email__ = "janole.zabel@tomtom.com"
__license__ = "Apache 2.0"
