#!/usr/bin/env python3
"""Tool to render maps in the example format.

Dependency: Geopandas, matplotlib

Usage: tools/render-map [db.sqlite] [--big] [--labels]

--big renders the image in a higher resolution.
--labels inscribes nodes and lines.

The output will be written to 'output.png'."""

import sys
from warnings import warn
from openlr_dereferencer.example_sqlite_map import ExampleMapReader
from openlr_dereferencer.maps.wgs84 import project_along_path
from shapely.geometry import Point, LineString
import matplotlib.pylab as pylab
import geopandas


def get_graph_lines(reader: ExampleMapReader) -> geopandas.GeoSeries:
    lines = [
        LineString([Point(*point) for point in line.coordinates()])
        for line in reader.get_lines()
    ]
    if not lines:
        warn("THE MAP HAS NO LINES")
    return geopandas.GeoSeries(lines)


def render_map(reader: ExampleMapReader, outfile: str, showlabels: bool = True):
    plot = get_graph_lines(reader).plot()

    if showlabels:
        # Text labels
        for point in reader.get_nodes():
            plot.text(*point.coordinates, point.node_id, weight="bold")

        for line in reader.get_lines():
            length = line.length
            path = list(line.coordinates())
            textpos = project_along_path(path, length / 3)
            plot.text(textpos.lon, textpos.lat, line.line_id, color="darkred", ma="center")

    fig = plot.get_figure()
    fig.savefig(outfile)


def render_sqlite(db: str, showlabels: bool = True):
    reader = ExampleMapReader(db)
    render_map(reader, "output.png", showlabels)


if __name__ == "__main__":
    if "--big" in sys.argv:
        pylab.rcParams["figure.figsize"] = 80, 60
    labels = "--labels" in sys.argv
    if len(sys.argv) > 1 and sys.argv[1][0] != "-":
        render_sqlite(sys.argv[1], labels)
    else:
        render_sqlite("db.sqlite", labels)
